source:
  - changed-files:
    - all-globs-to-any-file: 
      - 'src/**/*'
      - '!src/main/resources/*'
    
config:
  - changed-files:
    - any-glob-to-any-file: 
      - 'src/main/resources/*'
      
