source:
- any:
  - changed-files:
    - all-globs-to-any-file: 
      - 'src/**'
      - '!src/main/resouces/*'
      - '!src/test/resouces/*'

config:
- any:
  - changed-files:
    - any-glob-to-any-file: 
      - 'src/main/resouces/*'
      - 'src/test/resouces/*'
      
