source:
  - changed-files:
    - any-glob-to-any-file: 
      # common paths
      - 'src/**/*'
      # react
      - 'e2e/**/*'
      - 'public/**/*'
      - 'tests/**/*'
      # spring
      - 'src/main/resources/*'
      - 'src/test/resources/*'
         
config:
  - changed-files:
    - any-glob-to-any-file:
      # common paths
      - '*.*'
      # react
      - 'k28/**/*'
       # spring
      - 'src/main/resources/*'
      - 'src/test/resources/*'
      
