name: "Common PR Labeler"

on:
  workflow_call:
    inputs:
      labeler-token:
        required: true
        type: string

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout common actions repository for config
        uses: actions/checkout@v4
        with:
          repository: ulawil/common-wortkflows
          path: config

      - name: Copy labeler config
        run: cp config/.github/labeler.yml .github/labeler.yml

      - name: Run labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ inputs.labeler-token }}"
