name: "Common PR Labeler"

on:
  workflow_call:
    secrets:
      LABELER_TOKEN:
        required: true

jobs:
  # file-based-label:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Checkout common actions repository for config
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ulawil/common-wortkflows
  #         path: config

  #     - name: Copy labeler config
  #       run: cp config/.github/labeler.yml .github/labeler.yml

  #     - name: Label PR based on files changed
  #       uses: actions/labeler@v5
  #       with:
  #         repo-token: "${{ secrets.LABELER_TOKEN }}"

  review-based-label:
    # needs: file-based-label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on status and reviews
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.LABELER_TOKEN }}
          script: |
            const script = require('./.github/scripts/review-labeler.js');
            await script({ github, context })
            
