name: "Reusable PR Labeler"

on:
  workflow_call:
    secrets:
      LABELER_TOKEN:
        required: true

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout common actions repository for config and scripts
        uses: actions/checkout@v4
        with:
          repository: ulawil/common-wortkflows # todo change to program builder commons repo
          path: commons

      - name: Copy labeler config and scripts
        run: |
          mkdir -p .github/scripts
          cp commons/.github/labeler.yml .github/labeler.yml
          cp commons/.github/scripts/review-labeler.js .github/scripts/review-labeler.js
          echo "{}" > package.json

      - name: Label PR based on files changed
        uses: actions/labeler@v5 # todo change to commit hash
        with:
          repo-token: "${{ secrets.LABELER_TOKEN }}" # todo change to program builder repo token

      # - name: Label PR based on state and reviews
      #   uses: actions/github-script@v7 # todo change to commit hash
      #   with:
      #     github-token: ${{ secrets.LABELER_TOKEN }} # todo change to program builder repo token
      #     script: |
      #       const script = require('./.github/scripts/review-labeler.js');
      #       await script({ github, context })
            
