name: "Reusable PR Labeler"

on:
  workflow_call:

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Checkout common actions repository for config and scripts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: ulawil/common-wortkflows # todo change to program builder commons repo
          path: commons

      - name: Copy labeler config and scripts
        run: |
          mkdir -p .github/scripts
          cp commons/.github/labeler.yml .github/labeler.yml
          cp commons/.github/scripts/review-labeler.js .github/scripts/review-labeler.js
          echo "{}" > package.json

      - name: Label PR based on files changed
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # 5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR based on state and reviews
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # 7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/review-labeler.js');
            await script({ github, context })
            
